# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  host:
    description: 'ssh host'
  port:
    description: 'ssh port'
    default: 22
  passphrase:
    description: 'ssh key passphrase'
  username:
    description: 'ssh username'
  password:
    description: 'ssh password'
  sync:
    description: 'synchronous execution if multiple hosts'
    default: false
  use_insecure_cipher:
    description: 'include more ciphers with use_insecure_cipher'
    default: false
  cipher:
    description: 'the allowed cipher algorithms. If unspecified then a sensible'
  timeout:
    description: 'timeout for ssh to host'
    default: "30s"
  command_timeout:
    description: 'timeout for ssh command'
    default: "10m"
  key:
    description: 'content of ssh private key. ex raw content of ~/.ssh/id_rsa'
  key_path:
    description: 'path of ssh private key'
  fingerprint:
    description: 'sha256 fingerprint of the host public key'
  proxy_host:
    description: 'ssh proxy host'
  proxy_port:
    description: 'ssh proxy port'
    default: 22
  proxy_username:
    description: 'ssh proxy username'
  proxy_password:
    description: 'ssh proxy password'
  proxy_passphrase:
    description: 'ssh proxy key passphrase'
  proxy_timeout:
    description: 'timeout for ssh to proxy host'
    default: "30s"
  proxy_key:
    description: 'content of ssh proxy private key. ex raw content of ~/.ssh/id_rsa'
  proxy_key_path:
    description: 'path of ssh proxy private key'
  proxy_fingerprint:
    description: 'sha256 fingerprint of the proxy host public key'
  proxy_cipher:
    description: 'the allowed cipher algorithms. If unspecified then a sensible'
  proxy_use_insecure_cipher:
    description: 'include more ciphers with use_insecure_cipher'
    default: false
  script:
    description: 'execute commands'
  script_stop:
    description: 'stop script after first failure'
    default: false
  envs:
    description: 'pass environment variable to shell script'
  debug:
    description: 'enable debug mode'
    default: false    
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
